[features]
seeds = false

[programs.localnet]
hashusign = "7NSjhnPPnaP1bRocgazKQow3KXGky9MRErL1jZ5fAitj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
