[features]
seeds = false

[programs.localnet]
docuhash = "8t2FtnqVEoKw16CsyEDA9syRMi4At2rPNf337kwMtuw9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
