[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "wasm"

[dependencies]
hashusign = { path = "../programs/hashusign", features = ["cpi", "no-idl", "no-log-ix-name"] }
wasm-bindgen = "0.2.79"
