name: Lint

on: [push]

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: Prettier Check
        run: npm ci && npm run fmt

  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Format Check
        run: cargo fmt --all -- --check && cargo clippy -- -Dwarnings
